knp_paginator:
    page_range: 5                       # Pages in the pagination display range
    default_options:
        distinct: true
        page_name: page                  # The query parameter for the page number
        sort_field_name: sort            # The query parameter for sorting field
        sort_direction_name: direction   # The query parameter for sorting direction
        filter_field_name: filterField   # The query parameter for filter field
        filter_value_name: filterValue   # The query parameter for filter value
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Bootstrap 5 pagination template
